# Site settings
email: pch6828@hanyang.ac.kr
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: pch6828's Personal Blog
description: Personal Blog
url: "pch6828.github.io"
twitter_username: 
default_img: /we_can_undo_it.jpg/

# Profile settings
name: Jeong Ho Park
profile_img: https://avatars3.githubusercontent.com/u/48089354?s=460&u=74bc11bd647719371d8519d51602e503adeb15c4&v=4
profile: 한양대 재학중인 컴퓨터소프트웨어학부 학생입니다.<br>CSE student at Hanyang University in Korea<br><br>DBMS, 알고리즘, 자료구조 등에 흥미가 있습니다.<br>Interested in DBMS, Algorithm, Data Structure, etc...<br>
social:
  github: https://github.com/pch6828
  facebook: https://www.facebook.com/profile.php?id=100009329985343

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
